# example label to apply -> flexDiscoveryTraefik="t=traefik,c=traefik,tt=img,tm=contains"
# if using kubernetes add it as a environment variable
---
name: traefikFlex
global:
    base_url: http://${auto:host}:${auto:port}/
apis: 
  - event_type: traefikHealthSample
    url: health
    snake_to_camel: true
