# example label to apply -> flexDiscoveryTraefik="t=traefik,c=traefik,tt=img,tm=contains"
# if using kubernetes -> flexDiscoveryTraefik:"t_traefik.c_traefik.tt_img.tm_contains"
---
name: traefikFlex
global:
    base_url: http://${auto:host}:${auto:port}/
apis: 
  - event_type: traefikHealthSample
    url: health
    snake_to_camel: true
